import { useState } from 'react'
import Head from 'next/head'
import { getOptionsForVote } from '../utils/getRandomPokemon'
import { trpc } from '../utils/trpc'

export default function Home() {
  const [ids, setIds] = useState(getOptionsForVote())
  const [first, second] = ids
  const firstPokemon = trpc.get_pokemon_by_id.useQuery({ pokemonId: first })
  const secondPokemon = trpc.get_pokemon_by_id.useQuery({ pokemonId: second })
  // const firstPokemon = trpc.useQuery(["get_pokemon_by_id", { pokemonId: first }])
  console.log('firstPokemon.data', firstPokemon.data)
  console.log('secondPokemon.data', secondPokemon.data)

  if (!firstPokemon.data || !secondPokemon.data) {
    return <div>Loading...</div>
  }

  return (
    <div className='h-screen w-screen flex flex-col justify-center items-center'>
      <Head>
        <title>Roundest Pokemon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='text-center text-2xl '>Which Pokemon is rounder?</div>
      <div className='p-4'></div>
      <div className='border rounded-3xl p-8 flex justify-between items-center'>
        <div className='w-16 h-16 m-4 bg-blue-800'>
          <img
            src={
              firstPokemon.data?.pokemon.sprites.other?.['official-artwork']
                .front_default
            }
          />
        </div>
        <div className='p-8'>VS</div>
        <div className='w-16 h-16 m-4 bg-blue-800'>
          <img
            src={
              secondPokemon.data?.pokemon.sprites.other?.['official-artwork']
                .front_default
            }
          />
        </div>
      </div>
    </div>
  )
}
