/* eslint-disable @next/next/no-img-element */
import { useState } from 'react'
import Head from 'next/head'
import { getOptionsForVote } from '../utils/getRandomPokemon'
import { uppercaseFirstLetter } from '../utils/uppercaseFirstLetter'
import { trpc } from '../utils/trpc'

export default function Home() {
  const [ids, setIds] = useState(getOptionsForVote())
  const [first, second] = ids
  const firstPokemon = trpc.get_pokemon_by_id.useQuery({ pokemonId: first })
  const secondPokemon = trpc.get_pokemon_by_id.useQuery({ pokemonId: second })

  console.log('name type', typeof firstPokemon?.data?.pokemon?.name)

  const firstPokemonName = uppercaseFirstLetter(
    firstPokemon?.data?.pokemon?.name!
  )
  const secondPokemonName = uppercaseFirstLetter(
    secondPokemon?.data?.pokemon?.name!
  )

  console.log('firstPokemon.data', firstPokemon.data)
  console.log('secondPokemon.data', secondPokemon.data)

  if (!firstPokemon.data || !secondPokemon.data) {
    return <div>Loading...</div>
  }

  return (
    <div className='h-screen w-screen flex flex-col justify-center items-center'>
      <Head>
        <title>Roundest Pokemon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='text-center text-2xl '>Which Pokemon is Rounder?</div>
      <div className='p-4'></div>
      <div className='border rounded-3xl p-8 flex justify-between items-center'>
        <div className='flex-wrap'>
          <div className='text-center text-3xl mb-4'>{firstPokemonName}</div>
          <div className='w-64 h-64 bg-blue-800 rounded-full'>
            <img
              src={
                firstPokemon.data?.pokemon.sprites.other?.['official-artwork']
                  .front_default!
              }
              alt='pokemon1'
            />
          </div>
        </div>
        <div className='p-8 text-3xl'>VS</div>
        <div className='flex-wrap'>
          <div className='text-center text-3xl mb-4'>{secondPokemonName}</div>
          <div className='w-64 h-64 bg-blue-800 rounded-full'>
            <img
              src={
                secondPokemon.data?.pokemon.sprites.other?.['official-artwork']
                  .front_default!
              }
              alt='pokemon2'
            />
          </div>
        </div>
      </div>
    </div>
  )
}
